GARNAME = ggad
GARVERSION = 1.0

#BOOKS = $(WORKSRC)/ggad.sgml

DSSSL = book-html.dsl

FIGURES = figures/*

include ../../gar.mk

#post-extract:
#	cvs -d:pserver:anonymous@anoncvs.gnome.org:/cvs/gnome co GGAD/figures
#	cvs -d:pserver:anonymous@anoncvs.gnome.org:/cvs/gnome co GGAD/DocBook
#	cp -a $(FILEDIR) $(WORKSRC)

#JADE_FLAGS += -c $(WORKSRC)/catalog

#$(WORKSRC)/ggad.sgml: $(WORKSRC)/book.sgml
#	sed -e '1s/1\.0/1.1/' $< > $@
	
#post-clean:
#	rm -f ggad.sgml
