#!/usr/bin/python

"""Dump a HTML Help book into a SQL language file."""


import sys

from HTMLHelp.Generic import read
from HTMLHelp.MySQL import dump


def main():
	for arg in sys.argv[1:]:
		book = read(arg)

		dump(book)


if __name__ == '__main__':
	main()
