GARNAME = pango
GARVERSION = 1.2.1
MASTER_SITES = ftp://ftp.gtk.org/pub/gtk/v2.2/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = $(WORKSRC)/docs/pango-docs.sgml

FIGURES = layout.*

DSSSL = /usr/share/gtk-doc/gtk-doc.dsl
DCL = /usr/share/gtk-doc/gtk-doc.dcl

include ../../gar.mk

JADE_FLAGS += -w no-idref
