GARNAME = gtk+
GARVERSION = 2.2.1
MASTER_SITES = ftp://ftp.gtk.org/pub/gtk/v2.2/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.bz2

BOOKS = \
	$(WORKSRC)/docs/faq/gtk-faq.sgml \
	$(WORKSRC)/docs/reference/gdk/gdk-docs.sgml \
	$(WORKSRC)/docs/reference/gdk-pixbuf/gdk-pixbuf.sgml \
	$(WORKSRC)/docs/reference/gtk/gtk-docs.sgml \
	$(WORKSRC)/docs/tutorial/gtk-tut.sgml

FIGURES = images

include ../../gar.mk
