#!/bin/sh

rsync \
	-rtzv \
	--exclude '/cgi-bin' \
	--exclude '/books/download' \
	--exclude '/web/php' \
	--delete \
	"$@" \
	~/projects/htmlhelp/htdocs/ \
	jrfonseca@shell.berlios.de:/home/groups/htmlhelp/htdocs/

rsync \
	-rtzv \
	--delete \
	--exclude 'awstats*.txt' \
	"$@" \
	~/projects/htmlhelp/htdocs/cgi-bin/ \
	jrfonseca@shell.berlios.de:/home/groups/htmlhelp/cgi-bin/

rsync \
	-rtzv \
	--delete \
	--exclude '.svn' \
	--exclude 'config.inc.php' \
	"$@" \
	~/projects/htmlhelp/web/php/ \
	jrfonseca@shell.berlios.de:/home/groups/htmlhelp/htdocs/web/php/
